"use client";

import React, { useState, useEffect, useRef, useCallback } from "react";
import {
  ShieldCheck, Zap, ArrowLeft,
  ThumbsUp, ThumbsDown, Target, Lightbulb,
  Lock, Copy, Check, ChevronDown, ChevronUp,
  Star, Download, ExternalLink, Share2
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import { IntelligenceService, ProductIntelligence } from "@/lib/services/intelligence";
import Link from "next/link";
import { useParams } from "next/navigation";
import Navbar from "@/components/Navbar";

/* ─── Clipboard Hook ─── */
function useCopy() {
  const [copied, setCopied] = useState<string | null>(null);
  const copy = useCallback((text: string, key: string) => {
    navigator.clipboard.writeText(text).then(() => {
      setCopied(key);
      setTimeout(() => setCopied(null), 2000);
    });
  }, []);
  return { copied, copy };
}

export default function PublicReportPage() {
  const params = useParams();
  const id = params.id as string;
  const [intel, setIntel] = useState<ProductIntelligence | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const roadmapRef = useRef<HTMLDivElement>(null);
  const [showAllReviews, setShowAllReviews] = useState(false);
  const { copied, copy } = useCopy();

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  };

  const handleCopy = (text: string, key: string, label?: string) => {
    copy(text, key);
    showToast(label || "Copied to clipboard");
  };

  useEffect(() => {
    async function fetchReport() {
      if (!id) return;
      setLoading(true);
      try {
        const report = await IntelligenceService.getPublicReportById(id);
        if (report) {
          setIntel(report.data);
        } else {
          setError("Report not found");
        }
      } catch (e) {
        console.error("Fetch Report Error:", e);
        setError("Failed to load report");
      } finally {
        setLoading(false);
      }
    }
    fetchReport();
  }, [id]);

  const handleDownloadBrief = () => {
    if (!intel) return;
    const brief = [
      `ReviewVetter Intelligence Brief`,
      `Product: ${intel.productName}`,
      `Board Score: ${intel.score}/100 | Sentiment: ${intel.sentiment}`,
      ``,
      `INTELLIGENCE VECTORS`,
      `  Product Reliability: ${intel.details?.quality}%`,
      `  Market Favorability: ${intel.details?.value}%`,
      `  Logistics Efficiency: ${intel.details?.shipping}%`,
      `  Resolution Speed: ${intel.details?.support}%`,
      ``,
      `GROWTH OPPORTUNITY`,
      `  Issue: ${intel.revenueImpact?.leakageReason}`,
      `  Recovery Estimate: ${intel.revenueImpact?.recoveryEstimate}`,
      ``,
      `TOP STRENGTHS`,
      ...(intel.topPros?.map(p => `  • ${p}`) || []),
      ``,
      `TOP RISKS`,
      ...(intel.topCons?.map(c => `  • ${c}`) || []),
      ``,
      `SWOT ANALYSIS`,
      `  Strengths: ${intel.swot?.strengths?.join(", ")}`,
      `  Weaknesses: ${intel.swot?.weaknesses?.join(", ")}`,
      `  Opportunities: ${intel.swot?.opportunities?.join(", ")}`,
      `  Threats: ${intel.swot?.threats?.join(", ")}`,
      ``,
      `Generated by ReviewVetter | ${new Date().toLocaleDateString()}`,
    ].join("\n");

    const blob = new Blob([brief], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${intel.productName.replace(/\s+/g, "_")}_Brief.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToast("Brief downloaded!");
  };

  if (loading) return <div className="min-h-screen bg-[#f5f6fa] flex items-center justify-center font-black text-slate-400">Loading Intelligence...</div>;
  if (error || !intel) return (
    <div className="min-h-screen bg-[#f5f6fa] flex flex-col items-center justify-center gap-4">
      <h1 className="text-2xl font-black text-slate-900">{error || "Report Error"}</h1>
      <Link href="/" className="px-6 py-2 bg-indigo-600 text-white rounded-xl font-bold">Back to Home</Link>
    </div>
  );

  const score = intel.score;
  const isBullish = intel.sentiment === "BULLISH";
  const reviews = intel.sampleReviews || [];
  const visibleReviews = showAllReviews ? reviews : reviews.slice(0, 1);

  return (
    <div className="min-h-screen bg-[#f5f6fa]">
      <Navbar />

      <AnimatePresence>
        {toast && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="fixed top-4 right-4 z-50 flex items-center gap-2 bg-slate-900 text-white px-4 py-2.5 rounded-xl shadow-xl text-sm font-medium"
          >
            <Check className="w-4 h-4 text-emerald-400" />
            {toast}
          </motion.div>
        )}
      </AnimatePresence>

      <main className="max-w-6xl mx-auto px-6 py-8 space-y-5">
        <div className="bg-indigo-600 text-white px-4 py-2 rounded-xl text-center text-[10px] font-black uppercase tracking-widest flex items-center justify-center gap-2 shadow-sm">
          <Share2 className="w-3 h-3" /> Shared Intelligence Report — Read Only
        </div>

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5 flex-wrap">
              <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-indigo-50 text-indigo-600 text-[10px] font-black tracking-widest uppercase rounded">
                <Zap className="w-2.5 h-2.5 fill-current" /> AI Snapshot
              </span>
              {intel.sourceMix && Object.entries(intel.sourceMix).map(([s, c]) => (
                <span key={s} className="px-2 py-0.5 bg-white text-slate-500 text-[10px] font-bold rounded border border-slate-200">
                  {s}: {c as number} reviews
                </span>
              ))}
            </div>
            <h1 className="text-xl font-black text-slate-900 tracking-tight leading-tight">{intel.productName}</h1>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <div className="flex items-center gap-3 bg-white rounded-2xl px-4 py-2.5 border border-slate-200 shadow-sm">
              <div>
                <div className="text-[9px] font-black text-slate-400 uppercase tracking-widest leading-none mb-0.5">Board Score</div>
                <div className="text-xl font-black text-slate-900 leading-none tabular-nums">
                  {score}<span className="text-slate-300 text-xs font-bold">/100</span>
                </div>
              </div>
              <svg width="36" height="36" viewBox="0 0 36 36">
                <circle cx="18" cy="18" r="15" fill="none" stroke="#f1f5f9" strokeWidth="3" />
                <circle
                  cx="18" cy="18" r="15" fill="none"
                  stroke={isBullish ? "#10b981" : "#ef4444"}
                  strokeWidth="3"
                  strokeDasharray={`${(score / 100) * 94.2} 94.2`}
                  strokeLinecap="round"
                  transform="rotate(-90 18 18)"
                />
              </svg>
            </div>

            <button
              onClick={handleDownloadBrief}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl font-bold text-xs text-slate-600 bg-white border border-slate-200 hover:border-slate-300 transition-all shadow-sm"
            >
              <Download className="w-3.5 h-3.5" /> Brief
            </button>
            
            <button
              onClick={() => handleCopy(window.location.href, "share", "Report link copied!")}
              className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl font-bold text-xs text-white bg-slate-900 hover:bg-slate-800 transition-all shadow-sm"
            >
              <Share2 className="w-3.5 h-3.5" /> Share
            </button>
          </div>
        </div>

        {/* ── Content (Simplified version of Dashboard) ── */}
        <div className="grid md:grid-cols-5 gap-5">
          <div className="md:col-span-3 bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
            <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-5">Intelligence Vectors</h3>
            <div className="space-y-5">
              {[
                { label: "Product Reliability", value: intel.details.quality, color: "bg-indigo-500" },
                { label: "Market Favorability", value: intel.details.value, color: "bg-emerald-500" },
                { label: "Logistics Efficiency", value: intel.details.shipping, color: "bg-blue-500" },
                { label: "Resolution Speed", value: intel.details.support, color: "bg-amber-500" },
              ].map(({ label, value, color }) => (
                <div key={label}>
                  <div className="flex items-end justify-between mb-1.5">
                    <div className="text-sm font-bold text-slate-700">{label}</div>
                    <span className="text-lg font-black tabular-nums leading-none">{value}%</span>
                  </div>
                  <div className="h-2 bg-slate-100 rounded-full overflow-hidden">
                    <motion.div initial={{ width: 0 }} animate={{ width: `${value}%` }} className={cn("h-full rounded-full", color)} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="md:col-span-2 space-y-4">
            <SummaryCard title="What Customers Love" items={intel.topPros} color="emerald" Icon={ThumbsUp} />
            <SummaryCard title="Friction Points" items={intel.topCons} color="red" Icon={ThumbsDown} />
          </div>
        </div>

        {/* SWOT */}
        <div className="grid md:grid-cols-4 gap-4">
          <SWOTCard type="Strengths" items={intel.swot.strengths} color="emerald" Icon={ThumbsUp} />
          <SWOTCard type="Weaknesses" items={intel.swot.weaknesses} color="red" Icon={ThumbsDown} />
          <SWOTCard type="Opportunities" items={intel.swot.opportunities} color="indigo" Icon={Lightbulb} />
          <SWOTCard type="Threats" items={intel.swot.threats} color="amber" Icon={Target} />
        </div>

        {/* Roadmap */}
        <div ref={roadmapRef} className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm">
          <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-5">Strategic Roadmap</h3>
          <div className="grid md:grid-cols-2 gap-4">
            {intel.roadmap.map((step, i) => (
              <div key={i} className="flex gap-3 p-4 bg-slate-50 rounded-xl border border-slate-100">
                <div className="w-7 h-7 rounded-full bg-white border-2 border-slate-200 flex items-center justify-center text-[10px] text-indigo-600 font-black shrink-0">0{i + 1}</div>
                <div>
                  <h4 className="font-bold text-xs text-slate-800">{step.title}</h4>
                  <p className="text-[11px] text-slate-500 leading-relaxed">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

      </main>
    </div>
  );
}

function SummaryCard({ title, items, color, Icon }: any) {
  return (
    <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
      <div className="flex items-center gap-2 mb-3">
        <div className={`w-6 h-6 bg-${color}-50 rounded-lg flex items-center justify-center`}>
          <Icon className={`w-3 h-3 text-${color}-600`} />
        </div>
        <h3 className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{title}</h3>
      </div>
      <div className="space-y-2">
        {items.map((item: string, i: number) => (
          <div key={i} className="flex items-center gap-2 text-xs text-slate-700 font-medium">
            <div className={`w-1.5 h-1.5 rounded-full bg-${color}-400 shrink-0`} />
            {item}
          </div>
        ))}
      </div>
    </div>
  );
}

function SWOTCard({ type, items, color, Icon }: any) {
  return (
    <div className="bg-white rounded-2xl p-5 border border-slate-200 shadow-sm">
      <div className="flex items-center justify-between mb-4">
        <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{type}</h4>
        <div className={`w-6 h-6 rounded-lg flex items-center justify-center bg-${color}-50`}>
          <Icon className={`w-3 h-3 text-${color}-600`} />
        </div>
      </div>
      <ul className="space-y-2">
        {items.map((item: string, i: number) => (
          <li key={i} className="flex items-start gap-2 text-xs text-slate-600 leading-relaxed">
            <div className={`w-1 h-1 rounded-full bg-${color}-400 mt-1.5 shrink-0`} />
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}
